# Generated by Django 5.0.5 on 2024-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="important",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
